apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign4batch1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app1
  template:
    metadata:
      labels:
        app: k8s-app1
    spec:
      containers:
        - name: k8s-web-hello1
          image: umerarshad123/k8s-hello
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign4batch2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app2
  template:
    metadata:
      labels:
        app: k8s-app2
    spec:
      containers:
        - name: k8s-web-hello2
          image: umerarshad123/k8s-hello
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign4batch3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app3
  template:
    metadata:
      labels:
        app: k8s-app3
    spec:
      containers:
        - name: k8s-web-hello3
          image: umerarshad123/k8s-hello
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: assign4batch1
spec:
  type: NodePort
  selector:
    app: k8s-app1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: assign4batch2
spec:
  type: ClusterIP
  selector:
    app: k8s-app2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: assign4batch3
spec:
  type: LoadBalancer
  selector:
    app: k8s-app3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
